version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@3.0.0
  aws-cli: circleci/aws-cli@0.1.9
  aws_assume_role: lbh-hackit/aws_assume_role@0.1.0

executors:
  docker-python:
    docker:
      - image: circleci/python:3.7
  docker-terraform:
    docker:
      - image: "hashicorp/terraform:0.12.29"
  docker-dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1

references:
  workspace_root: &workspace_root "~"
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

commands:
  assume-role-and-persist-workspace-mosaic-production:
    description: "Assumes deployment role and persists credentials across jobs for Mosaic-Production"
    parameters:
      aws-account:
        type: string
    steps:
      - checkout
      - aws_assume_role/assume_role:
          account: <<parameters.aws-account>>
          profile_name: default
          role: "circleci-assume-role"
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws
  remove-resources:
    description: "Remove all resources created via Serverless"
    parameters:
      stage:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - setup_remote_docker
      - run:
          name: Install Node.js
          command: |
            curl -sL https://deb.nodesource.com/setup_13.x | bash -
            apt-get update && apt-get install -y nodejs
      - run:
          name: Install serverless CLI
          command: npm i -g serverless
      - run:
          name: Remove resources
          no_output_timeout: 40m
          command: |
            cd ./MosaicResidentInformationApi/
            sls remove --stage <<parameters.stage>>

jobs:
  assume-role-mosaic-production:
    executor: docker-python
    steps:
      - assume-role-and-persist-workspace-mosaic-production:
          aws-account: $AWS_ACCOUNT_PRODUCTION
  remove-mosaic-production-resources:
    executor: docker-dotnet
    steps:
      - remove-resources:
          stage: "mosaic-prod"

workflows:
  remove-resources-from-mosaic-production:
    jobs:
      - permit-mosaic-production-resources-removal:
          type: approval
          filters:
            branches:
              only: master
      - assume-role-mosaic-production:
          context: api-assume-role-social-care-production-context
          requires:
            - permit-mosaic-production-resources-removal
          filters:
            branches:
              only: master
      - remove-mosaic-production-resources:
          requires:
            - assume-role-mosaic-production
          filters:
            branches:
              only: master
